<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table, tr, td {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <h1>Table Generated by PHP</h1>
    <?php
        echo "<table style='width: 100%; height: 100%;'>";

        $id = "12341467873466234875724";
        $lastNumber = substr($id, strlen($id) - 1);
        $x = $lastNumber;

        if (intval($lastNumber) < 5) {
            $x += 4;
        }

        for ($i=0; $i < $x; $i++) { 
            echo "<tr>";
            
            if ($i == 0) {
                echo '<td colspan="3"><img src="my_firstname.jpg" alt="My First Name"></td>';
            } else if ($i == 1) {
                for ($j=0; $j < 3; $j++) { 
                    echo '<td>';
                    if ($j == 0) {
                        echo '<a href="#school">School</a>';
                    } else if ($j == 1) {
                        echo '<a href="#college">College</a>';
                    } else if ($j == 2) {
                        echo '<a href="#university">University</a>';
                    }
                    echo '</td>';
                }
            } else if ($i == 2) {
                for ($j=0; $j < 3; $j++) { 
                    if ($j == 0) {
                        echo '<td><a href="#home">HOME</a></td>';
                    } else if ($j == 1) {
                        echo '<td rowspan="3"><p>About myself</p></td>';
                    } else if ($j == 2) {
                        echo '<td rowspan="3"><marquee width="60%" direction="up" height="100px">' . $id . '</marquee></td>';
                    }
                }
            } else if ($i == 3) {
                echo '<td><a href="#contact_us">Contact us</a></td>';
            } else if ($i == 4) {
                echo '<td><a href="#about_us">About us</a></td>';
            } else if ($i == $x - 1) {
                echo '<td colspan="3"><span>&copy;My Name</span></td>';
            } else {
                echo '<td colspan="3">my university\'s name</td>';
            }

            echo "</tr>";
        }
        echo "</table>";
    ?>
</body>
</html>